### ISSUE TITLE
Count number of words in Microsoft Word

### ISSUE THREAD

**Issue by LividJava** [Terminal/DiscordForOffice#2]
I'd like to see a word count option integrated, granted i don't know if this is in the realm of possibility? as such its just a suggestion! still pretty cool stuff!!

**Comment by lepon01** [comment]
This might be possible

https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word.documentclass.words?view=word-pia

I'm not sure if this will work, but I'll check soon

**Comment by 7coil** [comment]
Word counts are too fine of a measurement to be used in Discord
~~also i can't find at what word the cursor is at~~

You get to see the page number instead in the latest version of DiscordForOffice.
